tunnel: c41e848e-c096-423f-8874-b15f75dfe9a3
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: dockerstackagycliauth.dpdns.org
    service: http://caddy:80
  - hostname: main.dockerstackagycliauth.dpdns.org
    service: http://caddy:80
  - hostname: ttyd.dockerstackagycliauth.dpdns.org
    service: http://caddy:80
  - hostname: dozzle.dockerstackagycliauth.dpdns.org
    service: http://caddy:80
  - hostname: files.dockerstackagycliauth.dpdns.org
    service: http://caddy:80
  - hostname: deploy.dockerstackagycliauth.dpdns.org
    service: http://caddy:80
  - hostname: auth.dockerstackagycliauth.dpdns.org
    service: http://caddy:80
  - service: http_status:404
